// UI Elements
export const els = {
  dropzone: document.getElementById('dropzone'),
  fileInput: document.getElementById('file-input'),
  fileList: document.getElementById('file-list'),
  
  modeGrid: document.getElementById('mode-grid'),
  modeAuto: document.getElementById('mode-auto'),
  modeCustom: document.getElementById('mode-custom'),
  settingsGrid: document.getElementById('settings-grid'),
  settingsAuto: document.getElementById('settings-auto'),
  settingsCustom: document.getElementById('settings-custom'),
  
  // Custom Grid UI elements
  btnSelectRegion: document.getElementById('btn-select-region'),
  customRegionX: document.getElementById('custom-region-x'),
  customRegionY: document.getElementById('custom-region-y'),
  customRegionW: document.getElementById('custom-region-w'),
  customRegionH: document.getElementById('custom-region-h'),
  btnRegionFull: document.getElementById('btn-region-full'),
  customCols: document.getElementById('custom-cols'),
  customRows: document.getElementById('custom-rows'),
  btnResetEqual: document.getElementById('btn-reset-equal'),
  btnAutoSnap: document.getElementById('btn-auto-snap'),
  btnSnapKeep: document.getElementById('btn-snap-keep'),
  
  // Rematch UI elements
  optRematch: document.getElementById('opt-rematch'),
  rematchSettings: document.getElementById('rematch-settings'),
  rematchMode: document.getElementById('rematch-mode'),
  rematchCustomSize: document.getElementById('rematch-custom-size'),
  rematchW: document.getElementById('rematch-w'),
  rematchH: document.getElementById('rematch-h'),
  rematchFit: document.getElementById('rematch-fit'),
  
  gridW: document.getElementById('grid-w'),
  gridH: document.getElementById('grid-h'),
  autoMinW: document.getElementById('auto-min-w'),
  autoMinH: document.getElementById('auto-min-h'),
  autoTolerance: document.getElementById('auto-tolerance'),
  autoRowGap: document.getElementById('auto-row-gap'),
  autoMergeGap: document.getElementById('auto-merge-gap'),
  optSkipEmpty: document.getElementById('opt-skip-empty'),
  optNaming: document.getElementById('opt-naming'),
  btnDetectGrid: document.getElementById('btn-detect-grid'),
  btnApplyAll: document.getElementById('btn-apply-all'),
  
  optBgRemoval: document.getElementById('opt-bg-removal'),
  bgRemovalSettings: document.getElementById('bg-removal-settings'),
  optBgRemovalMethod: document.getElementById('opt-bg-removal-method'),
  optBgRemovalModelSize: document.getElementById('opt-bg-removal-model-size'),
  chromakeySettingsGroup: document.getElementById('chromakey-settings-group'),
  aiSettingsGroup: document.getElementById('ai-settings-group'),
  bgColor: document.getElementById('bg-color'),
  btnPickColor: document.getElementById('btn-pick-color'),
  btnAutoDetectBg: document.getElementById('btn-auto-detect-bg'),
  bgTolerance: document.getElementById('bg-tolerance'),
  labelBgTolerance: document.getElementById('label-bg-tolerance'),
  optBgContiguous: document.getElementById('opt-bg-contiguous'),
  
  imageInfo: document.getElementById('image-info'),
  zoomLevel: document.getElementById('zoom-level'),
  btnZoomIn: document.getElementById('btn-zoom-in'),
  btnZoomOut: document.getElementById('btn-zoom-out'),
  btnZoomFit: document.getElementById('btn-zoom-fit'),
  btnZoomReset: document.getElementById('btn-zoom-reset'),
  
  canvasViewport: document.getElementById('canvas-viewport'),
  canvasContainer: document.getElementById('canvas-container'),
  canvas: document.getElementById('slicer-canvas'),
  loadingOverlay: document.getElementById('loading-overlay'),
  
  previewCount: document.getElementById('preview-count'),
  btnToggleAllSlices: document.getElementById('btn-toggle-all-slices'),
  previewGrid: document.getElementById('preview-grid'),
  
  exportStats: document.getElementById('export-stats'),
  btnExportActive: document.getElementById('btn-export-active'),
  btnExportAllBatch: document.getElementById('btn-export-all-batch'),
  
  exportProgressContainer: document.getElementById('export-progress-container'),
  progressStatusText: document.getElementById('progress-status-text'),
  progressPercent: document.getElementById('progress-percent'),
  progressFill: document.getElementById('progress-fill'),
  
  themeToggle: document.getElementById('btn-theme-toggle'),
  toastContainer: document.getElementById('toast-container'),
  
  tabSlices: document.getElementById('tab-slices'),
  tabAnimation: document.getElementById('tab-animation'),
  viewSlices: document.getElementById('view-slices'),
  viewAnimation: document.getElementById('view-animation'),
  animCanvas: document.getElementById('anim-canvas'),
  animNoFramesMsg: document.getElementById('anim-no-frames-msg'),
  btnAnimPlay: document.getElementById('btn-anim-play'),
  animFrameIdx: document.getElementById('anim-frame-idx'),
  animFrameTotal: document.getElementById('anim-frame-total'),
  animFps: document.getElementById('anim-fps'),
  labelAnimFps: document.getElementById('label-anim-fps'),
  btnExportGif: document.getElementById('btn-export-gif'),
  btnExportWebm: document.getElementById('btn-export-webm'),

  wsBtnSlicer: document.getElementById('ws-btn-slicer'),
  wsBtnVideo: document.getElementById('ws-btn-video'),
  slicerSidebarContent: document.getElementById('slicer-sidebar-content'),
  videoSidebarContent: document.getElementById('video-sidebar-content'),
  slicerViewportContent: document.getElementById('slicer-viewport-content'),
  videoViewportContent: document.getElementById('video-viewport-content'),
  
  videoDropzone: document.getElementById('video-dropzone'),
  videoFileInput: document.getElementById('video-file-input'),
  videoFileInfoContainer: document.getElementById('video-file-info-container'),
  videoCurrentName: document.getElementById('video-current-name'),
  videoCurrentMeta: document.getElementById('video-current-meta'),
  videoIntervalInput: document.getElementById('video-interval-input'),
  videoOptAllFrames: document.getElementById('video-opt-all-frames'),
  videoRangeStart: document.getElementById('video-range-start'),
  videoRangeEnd: document.getElementById('video-range-end'),
  btnVideoUseFull: document.getElementById('btn-video-use-full'),
  btnVideoExtract: document.getElementById('btn-video-extract'),
  
  wsVideoPlayer: document.getElementById('ws-video-player'),
  videoFramesGrid: document.getElementById('video-frames-grid'),
  videoGridPlaceholder: document.getElementById('video-grid-placeholder'),
  videoToolbarInfo: document.getElementById('video-toolbar-info'),
  videoTimeDisplay: document.getElementById('video-time-display'),
  videoOptBgRemoval: document.getElementById('video-opt-bg-removal'),
  videoBgRemovalSettings: document.getElementById('video-bg-removal-settings'),
  videoOptBgRemovalMethod: document.getElementById('video-opt-bg-removal-method'),
  videoOptBgRemovalModelSize: document.getElementById('video-opt-bg-removal-model-size'),
  videoChromakeySettingsGroup: document.getElementById('video-chromakey-settings-group'),
  videoAiSettingsGroup: document.getElementById('video-ai-settings-group'),
  videoBgColor: document.getElementById('video-bg-color'),
  videoBtnPickColor: document.getElementById('video-btn-pick-color'),
  videoBtnAutoDetectBg: document.getElementById('video-btn-auto-detect-bg'),
  videoBgTolerance: document.getElementById('video-bg-tolerance'),
  videoLabelBgTolerance: document.getElementById('video-label-bg-tolerance'),
  videoOptBgContiguous: document.getElementById('video-opt-bg-contiguous'),
  videoLoadingOverlay: document.getElementById('video-loading-overlay'),

  // Image Tools workspace elements
  wsBtnImgTools: document.getElementById('ws-btn-imgtools'),
  imgToolsSidebarContent: document.getElementById('imgtools-sidebar-content'),
  imgToolsViewportContent: document.getElementById('imgtools-viewport-content'),
  imgToolsDropzone: document.getElementById('imgtools-dropzone'),
  imgToolsFileInput: document.getElementById('imgtools-file-input'),
  imgToolsFileList: document.getElementById('imgtools-file-list'),
  imgToolsModeUpscale: document.getElementById('imgtools-mode-upscale'),
  imgToolsModeBgRemove: document.getElementById('imgtools-mode-bgremove'),
  imgToolsModeVector: document.getElementById('imgtools-mode-vector'),
  imgToolsModeCompress: document.getElementById('imgtools-mode-compress'),
  imgToolsSettingsUpscale: document.getElementById('imgtools-settings-upscale'),
  imgToolsSettingsBgRemove: document.getElementById('imgtools-settings-bgremove'),
  imgToolsSettingsVector: document.getElementById('imgtools-settings-vector'),
  imgToolsSettingsCompress: document.getElementById('imgtools-settings-compress'),
  bgremoveModel: document.getElementById('bgremove-model'),
  bgremoveFormat: document.getElementById('bgremove-format'),
  bgremoveQualityField: document.getElementById('bgremove-quality-field'),
  bgremoveQuality: document.getElementById('bgremove-quality'),
  labelBgremoveQuality: document.getElementById('label-bgremove-quality'),
  imgToolsBrushToolbar: document.getElementById('imgtools-brush-toolbar'),
  imgToolsBrushErase: document.getElementById('imgtools-brush-erase'),
  imgToolsBrushRestore: document.getElementById('imgtools-brush-restore'),
  imgToolsBrushSize: document.getElementById('imgtools-brush-size'),
  imgToolsBrushSizeLabel: document.getElementById('imgtools-brush-size-label'),
  btnImgToolsBrushUndo: document.getElementById('imgtools-brush-undo'),
  btnImgToolsBrushRedo: document.getElementById('imgtools-brush-redo'),
  btnImgToolsBrushReset: document.getElementById('imgtools-brush-reset'),
  imgToolsBrushCursor: document.getElementById('imgtools-brush-cursor'),
  upscaleAlgorithm: document.getElementById('upscale-algorithm'),
  upscaleAiModelField: document.getElementById('upscale-ai-model-field'),
  upscaleAiModel: document.getElementById('upscale-ai-model'),
  upscaleScale: document.getElementById('upscale-scale'),
  upscaleFormat: document.getElementById('upscale-format'),
  upscaleQualityField: document.getElementById('upscale-quality-field'),
  upscaleQuality: document.getElementById('upscale-quality'),
  labelUpscaleQuality: document.getElementById('label-upscale-quality'),
  compressFormat: document.getElementById('compress-format'),
  compressQualityField: document.getElementById('compress-quality-field'),
  compressQuality: document.getElementById('compress-quality'),
  labelCompressQuality: document.getElementById('label-compress-quality'),
  compressStats: document.getElementById('compress-stats'),
  vectorMode: document.getElementById('vector-mode'),
  vectorTraceOptions: document.getElementById('vector-trace-options'),
  vectorPreset: document.getElementById('vector-preset'),
  vectorColors: document.getElementById('vector-colors'),
  labelVectorColors: document.getElementById('label-vector-colors'),
  btnImgToolsProcess: document.getElementById('btn-imgtools-process'),
  btnImgToolsProcessAll: document.getElementById('btn-imgtools-process-all'),
  btnImgToolsDownload: document.getElementById('btn-imgtools-download'),
  btnImgToolsDownloadAll: document.getElementById('btn-imgtools-download-all'),
  btnImgToolsOpenFolder: document.getElementById('btn-imgtools-open-folder'),
  btnImgToolsSaveFolder: document.getElementById('btn-imgtools-save-folder'),
  imgToolsFolderHint: document.getElementById('imgtools-folder-hint'),
  imgToolsLoadingOverlay: document.getElementById('imgtools-loading-overlay'),
  imgToolsLoadingText: document.getElementById('imgtools-loading-text'),
  imgToolsInfo: document.getElementById('imgtools-info'),
  imgToolsResultMeta: document.getElementById('imgtools-result-meta'),
  imgToolsZoomLevel: document.getElementById('imgtools-zoom-level'),
  btnImgToolsZoomIn: document.getElementById('btn-imgtools-zoom-in'),
  btnImgToolsZoomOut: document.getElementById('btn-imgtools-zoom-out'),
  btnImgToolsZoomFit: document.getElementById('btn-imgtools-zoom-fit'),
  btnImgToolsZoomReset: document.getElementById('btn-imgtools-zoom-reset'),
  imgToolsPaneOriginal: document.getElementById('imgtools-pane-original'),
  imgToolsPaneResult: document.getElementById('imgtools-pane-result'),
  imgToolsOutputContent: document.getElementById('imgtools-output-content'),
  imgToolsExportSummary: document.getElementById('imgtools-export-summary')
};

// Canvas Context
export const ctx = els.canvas.getContext('2d');
